version: '3.7'
services:
  web:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    # environment:
      # GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # Template File: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
    volumes:
      - ../Data/config:/etc/gitlab
      - ../Config/gitlab.rb:/etc/gitlab/gitlab.rb
      - ../Data/logs:/var/log/gitlab
      - ../Data/data:/var/opt/gitlab
